easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\TblPost
       - App\Entity\TblStory
       - App\Entity\TblAuthor
  

    # ...
   design:

        # the value of this option can be any valid CSS color
       brand_color: 'green'

        # if the color includes a '%', you must double it to escape it in the YAML file
